### ISSUE TITLE
Mapping already exists 

### ISSUE THREAD

**Issue by SolarAquarion** [JBakamovic/cxxd-vim#4]
![Screenshot-2019-09-19-07-51-07](https://user-images.githubusercontent.com/5307016/65241733-4fd67780-dab2-11e9-8582-ccaa76ad59f7.png)

**Comment by JBakamovic** [comment]
You have another plugin which uses `F3` (line 145, 146) and `F5` (line 159, 160) mappings. You can either remap those to different values in `cxxd-vim` plugin ([here](https://github.com/JBakamovic/cxxd-vim/blob/master/plugin/cxxd.vim#L145-L162)) or in another plugin you're using.

**Comment by JBakamovic** [comment]
I am closing this issue as it is rather per-user configuration issue.
