### ISSUE TITLE
Error while launching VIM with CXXD

### ISSUE THREAD

**Issue by rajtendulkar** [JBakamovic/cxxd-vim#5]
Error detected while processing <HOME_DIR>/.vim/bundle/cxxd-vim/plugin/cxxd/server.vim:
line   10:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<HOME_DIR>/.local/lib/python2.7/site-packages/cxxd.py", line 17
    class XXDParser(object, metaclass=ABCMeta):
                                     ^
SyntaxError: invalid syntax
Error detected while processing <HOME_DIR>/.vim/bundle/cxxd-vim/plugin/cxxd.vim:
line  153:
E227: mapping already exists for ^\s
line  155:
E227: mapping already exists for ^\d
Press ENTER or type command to continue

**Comment by JBakamovic** [comment]
You have another Vim plugin which conflicts with the mappings of cxxd-vim. In particular, `Ctrl + \ + s` and `Ctrl + \ + d` are in conflict so you can either [change them](https://github.com/JBakamovic/cxxd-vim/blob/master/plugin/cxxd.vim#L145-L162) to something else or change other one(s) from another plugin(s).

**Comment by rajtendulkar** [comment]
I still got this error:

Error detected while processing <HOME_DIR>/.vim/bundle/cxxd-vim/plugin/cxxd/server.vim:
line 10:
Traceback (most recent call last):
File "", line 1, in
File "<HOME_DIR>/.local/lib/python2.7/site-packages/cxxd.py", line 17
class XXDParser(object, metaclass=ABCMeta):
^
SyntaxError: invalid syntax

**Comment by JBakamovic** [comment]
That seems like a problem from [another plugin](https://github.com/skalidindi3/cxxd) you have installed. Funny enough, that plugin repository shares the same name as repository which is hosting C++ server implementation that this (cxxd-vim) plugin is using ([cxxd](https://github.com/JBakamovic/cxxd)).

**Comment by rajtendulkar** [comment]
Thanks for the pointer. I had Python module cxxd installed. The solution was:
`pip  remove cxxd`
